// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrq7yy7QPW0L_DfR-4xOILUJ92_iysjek',
    appId: '1:306276383743:web:2bcfea15e5c7a7e84885ca',
    messagingSenderId: '306276383743',
    projectId: 'shop-app-6db3b',
    authDomain: 'shop-app-6db3b.firebaseapp.com',
    storageBucket: 'shop-app-6db3b.firebasestorage.app',
    measurementId: 'G-8PNH0QMGV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqT8p-hDjuFqbZI4rrheAt2NZTGNzwebo',
    appId: '1:306276383743:android:eb598fc742da033f4885ca',
    messagingSenderId: '306276383743',
    projectId: 'shop-app-6db3b',
    storageBucket: 'shop-app-6db3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvGDH92YvqWvVxu0vGCcMQMz7_oqV5s8o',
    appId: '1:306276383743:ios:e45016934788545f4885ca',
    messagingSenderId: '306276383743',
    projectId: 'shop-app-6db3b',
    storageBucket: 'shop-app-6db3b.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvGDH92YvqWvVxu0vGCcMQMz7_oqV5s8o',
    appId: '1:306276383743:ios:e45016934788545f4885ca',
    messagingSenderId: '306276383743',
    projectId: 'shop-app-6db3b',
    storageBucket: 'shop-app-6db3b.firebasestorage.app',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrq7yy7QPW0L_DfR-4xOILUJ92_iysjek',
    appId: '1:306276383743:web:049e74e5bdc957f24885ca',
    messagingSenderId: '306276383743',
    projectId: 'shop-app-6db3b',
    authDomain: 'shop-app-6db3b.firebaseapp.com',
    storageBucket: 'shop-app-6db3b.firebasestorage.app',
    measurementId: 'G-Z5K1LZVYBP',
  );
}
